// Mocks generated by Mockito 5.4.5 from annotations
// in ditonton/test/data/repositories/tv_series_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ditonton/data/datasources/tv_series_local_data_source.dart'
    as _i6;
import 'package:ditonton/data/datasources/tv_series_remote_data_source.dart'
    as _i3;
import 'package:ditonton/data/models/tv_series_detail_model.dart' as _i2;
import 'package:ditonton/data/models/tv_series_model.dart' as _i5;
import 'package:ditonton/data/models/tv_series_table.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTvSeriesDetailResponse_0 extends _i1.SmartFake
    implements _i2.TvSeriesDetailResponse {
  _FakeTvSeriesDetailResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TvSeriesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRemoteDataSource extends _i1.Mock
    implements _i3.TvSeriesRemoteDataSource {
  MockTvSeriesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.TvSeriesModel>> getNowPlayingTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingTvSeries, []),
            returnValue: _i4.Future<List<_i5.TvSeriesModel>>.value(
              <_i5.TvSeriesModel>[],
            ),
          )
          as _i4.Future<List<_i5.TvSeriesModel>>);

  @override
  _i4.Future<List<_i5.TvSeriesModel>> getPopularTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTvSeries, []),
            returnValue: _i4.Future<List<_i5.TvSeriesModel>>.value(
              <_i5.TvSeriesModel>[],
            ),
          )
          as _i4.Future<List<_i5.TvSeriesModel>>);

  @override
  _i4.Future<List<_i5.TvSeriesModel>> getTopRatedTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTvSeries, []),
            returnValue: _i4.Future<List<_i5.TvSeriesModel>>.value(
              <_i5.TvSeriesModel>[],
            ),
          )
          as _i4.Future<List<_i5.TvSeriesModel>>);

  @override
  _i4.Future<_i2.TvSeriesDetailResponse> getTvSeriesDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesDetail, [id]),
            returnValue: _i4.Future<_i2.TvSeriesDetailResponse>.value(
              _FakeTvSeriesDetailResponse_0(
                this,
                Invocation.method(#getTvSeriesDetail, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.TvSeriesDetailResponse>);

  @override
  _i4.Future<List<_i5.TvSeriesModel>> getTvSeriesRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesRecommendations, [id]),
            returnValue: _i4.Future<List<_i5.TvSeriesModel>>.value(
              <_i5.TvSeriesModel>[],
            ),
          )
          as _i4.Future<List<_i5.TvSeriesModel>>);

  @override
  _i4.Future<List<_i5.TvSeriesModel>> searchTvSeries(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTvSeries, [query]),
            returnValue: _i4.Future<List<_i5.TvSeriesModel>>.value(
              <_i5.TvSeriesModel>[],
            ),
          )
          as _i4.Future<List<_i5.TvSeriesModel>>);
}

/// A class which mocks [TvSeriesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesLocalDataSource extends _i1.Mock
    implements _i6.TvSeriesLocalDataSource {
  MockTvSeriesLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> insertWatchlist(_i7.TvSeriesTable? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [tvSeries]),
            returnValue: _i4.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#insertWatchlist, [tvSeries]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> removeWatchlist(_i7.TvSeriesTable? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [tvSeries]),
            returnValue: _i4.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#removeWatchlist, [tvSeries]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<_i7.TvSeriesTable?> getTvSeriesById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesById, [id]),
            returnValue: _i4.Future<_i7.TvSeriesTable?>.value(),
          )
          as _i4.Future<_i7.TvSeriesTable?>);

  @override
  _i4.Future<List<_i7.TvSeriesTable>> getWatchlistTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTvSeries, []),
            returnValue: _i4.Future<List<_i7.TvSeriesTable>>.value(
              <_i7.TvSeriesTable>[],
            ),
          )
          as _i4.Future<List<_i7.TvSeriesTable>>);
}
